### ISSUE TITLE
./run-mtgo issue 'unknown shorthand flag: 'o' in -o

### ISSUE THREAD

**Issue by kirkforaday** [pauleve/docker-mtgo#138] opened 2021-09-08 16:11 UTC
Having an issue getting this up and running. No matter how I go about it, I always end up in this same place.

`./run-mtgo
docker volume create mtgo-data-ryankirk
mtgo-data-user
docker run --rm -v mtgo-data-user:/home/wine/.wine/host -o true
unknown shorthand flag: 'o' in -o
See 'docker run --help'.`

Any suggestions for what's going on here?

**Comment by jlessard93** [comment] 2021-11-13 04:41
I am having the same issue as @kirkforaday . I am on a silicon Mac and just running the command as `./run-mtgo` in the directory that I ran the curl command.

**Comment by pauleve** [comment] 2021-11-17 14:50
Can you post the full output of the `./run-mtgo` command?
If possible, insert `set -x`  in line 2 of the script to have more debug information.

**Comment by jlessard93** [comment] 2021-11-18 03:00
Here is the output without the extra debugging

 ./run-mtgo
`IMAGE=./run-mtgo
CUSTOM DOCKER OPTS= -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug --
Updating image ./run-mtgo...
run(): docker pull ./run-mtgo
invalid reference format
Using network interface 'en0'
run(): open -a XQuartz
socat on 192.168.86.218 forwarding to /private/tmp/com.apple.launchd.1RzxX0LAJ1/org.xquartz:0
run(): docker run --privileged --rm -e DISPLAY -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug -- -v mtgo-data-computername:/home/wine/.wine/host/ -v mtgo-data-computername:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/zoneinfo/America/New_York --name mtgo_running ./run-mtgo mtgo
unknown shorthand flag: 'o' in -o
See 'docker run --help'.`


Here is the output with the extra logs. I tried to format it so it was more easily readable.
./run-mtgo
+ defaultcmd=mtgo
+ image=panard/mtgo:latest
+ name=mtgo_running
+ cmd=mtgo
+ cmdargs=
+ opts=
+ data=mtgo-data-computername
+ do_sound=false
+ do_update=false
+ local_data=/Users/computername/.local/share/mtgo
+ lopts=dry-run,help,winecfg,shell,cmd:,name:
+ lopts=dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset
+ lopts=dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound
+ lopts=dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test
+ lopts=dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz
+ lopts=dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update
+ lopts=dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug
+ getopt=getopt
+ brew_getopt=/usr/local/opt/gnu-getopt/bin/getopt
+ [[ darwin21 == darwin* ]]
+ '[' -x /usr/local/opt/gnu-getopt/bin/getopt ']'
++ getopt -n ./run-mtgo -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug -- ./run-mtgo
+ args=' -- ./run-mtgo -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug -- ./run-mtgo'
+ '[' 0 -ne 0 ']'
+ eval set -- -- ./run-mtgo -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug -- ./run-mtgo
++ set -- -- ./run-mtgo -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug -- ./run-mtgo
+ do_run=true
+ do_reset=false
+ do_test=false
+ mytz=
+ detect_tz=false
+ '[' -z '' ']'
+ detect_tz=true
+ '[' -n -- ']'
+ case "${1:-}" in
+ shift
+ shift
+ '[' -n -o ']'
+ '[' -n hv:u:e: ']'
+ opts=' -o'
+ shift
+ '[' -n --longoptions ']'
+ opts=' -o hv:u:e:'
+ shift
+ '[' -n dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug ']'
+ opts=' -o hv:u:e: --longoptions'
+ shift
+ '[' -n -- ']'
+ opts=' -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug'
+ shift
+ '[' -n ./run-mtgo ']'
+ opts=' -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug --'
+ shift
+ '[' -n '' ']'
+ image=./run-mtgo
+ do_update=true
+ shift
+ '[' -n '' ']'
+ echo IMAGE=./run-mtgo
IMAGE=./run-mtgo
+ '[' -n ' -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug --' ']'
+ echo 'CUSTOM DOCKER OPTS= -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug --'
CUSTOM DOCKER OPTS= -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug --
++ id -u
+ _host_uid=501
+ [[ 501 == 0 ]]
+ true
+ '[' -f /etc/timezone ']'
+ '[' -L /etc/localtime ']'
++ readlink /etc/localtime
++ cut -d/ -f 5-
+ mytz=zoneinfo/America/New_York
+ false
+ true
+ echo 'Updating image ./run-mtgo...'
Updating image ./run-mtgo...
+ run docker pull ./run-mtgo
+ echo 'run(): docker' pull ./run-mtgo
run(): docker pull ./run-mtgo
+ true
+ docker pull ./run-mtgo
invalid reference format
+ docker volume inspect mtgo-data-computername
+ '[' 1 -ne 0 ']'
+ set -e
+ run docker volume create mtgo-data-computername
+ echo 'run(): docker' volume create mtgo-data-computername
run(): docker volume create mtgo-data-computername
+ true
+ docker volume create mtgo-data-computername
mtgo-data-computername
+ old_data=mtgo-data
+ set +e
+ docker volume inspect mtgo-data
+ '[' 1 -eq 0 ']'
+ set -e
+ run docker run --rm -v mtgo-data-computername:/home/wine/.wine/host ./run-mtgo true
+ echo 'run(): docker' run --rm -v mtgo-data-computername:/home/wine/.wine/host ./run-mtgo true
run(): docker run --rm -v mtgo-data-computername:/home/wine/.wine/host ./run-mtgo true
+ true
+ docker run --rm -v mtgo-data-computername:/home/wine/.wine/host ./run-mtgo true
docker: invalid reference format.
See 'docker run --help'.

**Comment by pauleve** [comment] 2021-11-19 09:36
Thanks. It seems caused by the command `getopt`.
Has the `brew install gnu-getopt` command succeeded?
The output of the following commands would help:
- `which getopt`
- `type getopt`
- `brew ls --verbose gnu-getopt`

**Comment by jlessard93** [comment] 2021-11-20 01:09
I reran the `brew install gnu-getopt` command and made sure to add the following to my shell resource file `export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"`. I was able to get past the error I was having but encountered a new one.
`011c:err:crypt:CRYPT_ImportSystemRootCertsToReg Failed to import system certs into registry, 00000057` is then following by 
![image](https://user-images.githubusercontent.com/6863261/142708771-a31a6bf4-4569-4748-885e-6a4f4c0bb1f8.png)
Looking at the logs mentioned in the error I see the following...
`$ pwd`
`/home/wine/.wine/drive_c/users/wine/VSDf08f.tmp`
`$ cat install.log`
`The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [ProcessorArchitecture] = Intel {string}
Property: [VersionNT] = 6.1.1 {version}
Running checks for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Unable to read registry value
Not setting value for property 'DotNet45Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Unable to read registry value
Not setting value for property 'DotNet45Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)':
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Skipping ByPassIf because Property 'DotNet45Full_Release' was not defined
Skipping ByPassIf because Property 'DotNet45Full_OSIntegrated' was not defined
Result of running operator 'ValueEqualTo' on property 'AdminUser' and value 'false': false
Result of running operator 'VersionLessThan' on property 'VersionNT' and value '6.0.0': false
Result of running operator 'ValueEqualTo' on property 'ProcessorArchitecture' and value 'IA64': false
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Install'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Skipping ByPassIf because Property 'DotNet45Full_Release' was not defined
Skipping ByPassIf because Property 'DotNet45Full_OSIntegrated' was not defined
Result of running operator 'ValueNotExists' on property 'DotNet45Full_OSIntegrated': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.5.2 (x86 and x64)' RunCheck result: Install Needed
Running checks for package 'Windows Installer 4.5', phase BuildList
Looking up path for special folder 'WindowsFolder'
Running check with folder 'C:\windows\System32' and file 'msi.dll'
Attempting to find file 'C:\windows\System32\msi.dll'
File version is '4.5.6001.22308'
Setting value '4.5.6001.22308 {version}' for property 'VersionMsiDll'
The following properties have been set for package 'Windows Installer 4.5':
Property: [VersionMsiDll] = 4.5.6001.22308 {version}
Running checks for command 'WindowsInstaller4_5\WindowsXP-KB942288-v3-x86.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsi' and value '4.5': true
Result of checks for command 'WindowsInstaller4_5\WindowsXP-KB942288-v3-x86.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsXP-KB958655-v2-x86-ENU.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22299': true
Result of checks for command 'WindowsInstaller4_5\WindowsXP-KB958655-v2-x86-ENU.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsServer2003-KB942288-v4-x86.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsi' and value '4.5': true
Result of checks for command 'WindowsInstaller4_5\WindowsServer2003-KB942288-v4-x86.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsServer2003-KB958655-v2-x86-ENU.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22299': true
Result of checks for command 'WindowsInstaller4_5\WindowsServer2003-KB958655-v2-x86-ENU.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsServer2003-KB942288-v4-x64.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsi' and value '4.5': true
Result of checks for command 'WindowsInstaller4_5\WindowsServer2003-KB942288-v4-x64.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsServer2003.WindowsXP-KB958655-v2-x64-ENU.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22299': true
Result of checks for command 'WindowsInstaller4_5\WindowsServer2003.WindowsXP-KB958655-v2-x64-ENU.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\Windows6.0-KB958655-v2-x86.MSU'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22308': true
Result of checks for command 'WindowsInstaller4_5\Windows6.0-KB958655-v2-x86.MSU' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\Windows6.0-KB958655-v2-x64.MSU'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22308': true
Result of checks for command 'WindowsInstaller4_5\Windows6.0-KB958655-v2-x64.MSU' is 'Bypass'
'Windows Installer 4.5' RunCheck result: No Install Needed
EULA for components 'Microsoft .NET Framework 4.5.2 (x86 and x64)' was accepted.
Copying files to temporary directory "C:\users\wine\VSDf08f.tmp\"
Downloading files to "C:\users\wine\VSDf08f.tmp\"
(11/20/2021 12:59:13 AM) Downloading 'DotNetFX452\NDP452-KB2901954-Web.exe' from 'http://go.microsoft.com/fwlink/?linkid=328843&clcid=0x409' to 'C:\users\wine\VSDf08f.tmp\'
Download completed at 11/20/2021 12:59:14 AM
Downloading failed with HRESULT=-2146697191`

**Comment by pauleve** [comment] 2021-11-20 14:32
I modified `run-mtgo` so it will find the right getopt (the homebrew path changed recently apparently).

**Comment by pauleve** [comment] 2021-11-20 15:01
For the new error, try doing `./run-mtgo --reset` as the previous error may have messed up the setup.

**Comment by mbenzvi** [comment] 2021-11-20 15:11
I'm trying ./run-mtgo --reset and am still getting the error in the original post (and it looks like another one). Here is the total output from running the command:

IMAGE=--reset
CUSTOM DOCKER OPTS= -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug -- ./run-mtgo
Updating image --reset...
run(): docker pull --reset
unknown flag: --reset
See 'docker pull --help'.
Using network interface 'en0'
run(): open -a XQuartz
socat on 192.168.0.15 forwarding to /private/tmp/com.apple.launchd.8gAn1EtvjS/org.xquartz:0
run(): docker run --privileged --rm -e DISPLAY -o hv:u:e: --longoptions dry-run,help,winecfg,shell,cmd:,name:,data-volume:,reset,sound,disable-sound,test,no-tz,update,debug -- ./run-mtgo -v mtgo-data-mbenzvi:/home/wine/.wine/host/ -v mtgo-data-mbenzvi:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/zoneinfo/America/New_York --name mtgo_running --reset mtgo
unknown shorthand flag: 'o' in -o
See 'docker run --help'.

Not sure if its another issue or the same one

**Comment by pauleve** [comment] 2021-11-21 14:30
@mbenzvi please provide the output of commands of https://github.com/pauleve/docker-mtgo/issues/138#issuecomment-973908008, especially `brew ls --verbose gnu-getopt`

**Comment by mbenzvi** [comment] 2021-11-21 15:38
Here's what I got. I am fairly ignorant about these things and this is my first try getting MTGO on my mac:

mba-210118:~ mbenzvi$ brew ls --verbose gnu-getopt
/opt/homebrew/Cellar/gnu-getopt/2.37.2/INSTALL_RECEIPT.json
/opt/homebrew/Cellar/gnu-getopt/2.37.2/bin/getopt
/opt/homebrew/Cellar/gnu-getopt/2.37.2/.brew/gnu-getopt.rb
/opt/homebrew/Cellar/gnu-getopt/2.37.2/ChangeLog
/opt/homebrew/Cellar/gnu-getopt/2.37.2/AUTHORS
/opt/homebrew/Cellar/gnu-getopt/2.37.2/etc/bash_completion.d/getopt
/opt/homebrew/Cellar/gnu-getopt/2.37.2/README
/opt/homebrew/Cellar/gnu-getopt/2.37.2/COPYING
/opt/homebrew/Cellar/gnu-getopt/2.37.2/NEWS
/opt/homebrew/Cellar/gnu-getopt/2.37.2/share/man/man1/getopt.1
mba-210118:~ mbenzvi$ which getopt
/usr/bin/getopt
mba-210118:~ mbenzvi$ type getopt
getopt is /usr/bin/getopt


Let me know if I should run any other commands. Thanks for the help!

**Comment by pauleve** [comment] 2021-11-22 08:31
@mbenzvi try doing
```
PATH=/opt/homebrew/Cellar/gnu-getopt/2.37.2/bin/:$PATH ./run-mtgo
```
I'll improve the `run-mtgo` script to auto-detect this.

**Comment by mbenzvi** [comment] 2021-11-22 12:19
That did something, but things got stuck along the way and has been doing nothing for about 45 minutes now. I no longer have the unknown shorthand flag error, so let me know if you would like me to open a new issue for this since the original one seems to be resolved:

Here is what I got from the command you recommended. Let me know if you want it in a different format that might be more readable:

`IMAGE=panard/mtgo:latest
Using network interface 'en0'
run(): open -a XQuartz
socat on 192.168.0.15 forwarding to /private/tmp/com.apple.launchd.8gAn1EtvjS/org.xquartz:0
run(): docker run --privileged --rm -e DISPLAY -v mtgo-data-mbenzvi:/home/wine/.wine/host/ -v mtgo-data-mbenzvi:/home/wine/.wine/drive_c/users/ -e WINE_X11_NO_MITSHM=1 --net=host --ipc=host -e TZ=/usr/share/zoneinfo/zoneinfo/America/New_York --name mtgo_running panard/mtgo:latest mtgo
Unable to find image 'panard/mtgo:latest' locally
latest: Pulling from panard/mtgo
1e6173dfff3a: Pulling fs layer
1315546f336a: Pulling fs layer
adb817662d75: Pulling fs layer
2a1fc8fc5e08: Pulling fs layer
5619c90dabd6: Pulling fs layer
98b980a03d52: Pulling fs layer
72a6c1be78f1: Pulling fs layer
cb199d3b21c1: Pulling fs layer
3d91420f21b4: Pulling fs layer
a4574c541f33: Pulling fs layer
28bd37c7bf2a: Pulling fs layer
16a97a11f1a2: Pulling fs layer
d01c6e4644fa: Pulling fs layer
2a1fc8fc5e08: Waiting
5619c90dabd6: Waiting
98b980a03d52: Waiting
72a6c1be78f1: Waiting
cb199d3b21c1: Waiting
3d91420f21b4: Waiting
a4574c541f33: Waiting
28bd37c7bf2a: Waiting
16a97a11f1a2: Waiting
d01c6e4644fa: Waiting
1e6173dfff3a: Download complete
2a1fc8fc5e08: Verifying Checksum
2a1fc8fc5e08: Download complete
5619c90dabd6: Verifying Checksum
5619c90dabd6: Download complete
1e6173dfff3a: Pull complete
98b980a03d52: Verifying Checksum
98b980a03d52: Download complete
72a6c1be78f1: Download complete
cb199d3b21c1: Verifying Checksum
cb199d3b21c1: Download complete
1315546f336a: Download complete
1315546f336a: Pull complete
3d91420f21b4: Verifying Checksum
3d91420f21b4: Download complete
28bd37c7bf2a: Verifying Checksum
28bd37c7bf2a: Download complete
16a97a11f1a2: Verifying Checksum
16a97a11f1a2: Download complete
d01c6e4644fa: Verifying Checksum
d01c6e4644fa: Download complete
adb817662d75: Download complete
adb817662d75: Pull complete
2a1fc8fc5e08: Pull complete
5619c90dabd6: Pull complete
98b980a03d52: Pull complete
72a6c1be78f1: Pull complete
cb199d3b21c1: Pull complete
3d91420f21b4: Pull complete
a4574c541f33: Verifying Checksum
a4574c541f33: Download complete
a4574c541f33: Pull complete
28bd37c7bf2a: Pull complete
16a97a11f1a2: Pull complete
d01c6e4644fa: Pull complete
Digest: sha256:d7c75d2ff15f1a238ef8160bd0adc9607e6232bfd21f308a939b073d0dc5c8fc
Status: Downloaded newer image for panard/mtgo:latest
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
winetricks gdiplus=native sound=alsa winegstreamer=disabled wmp=disabled
Executing mkdir -p /home/wine
Using winetricks 20210206-next - sha256sum: f543edcc89729647fb2226d70fe6efd0dc5ac61e237eaa207a0d461a61b2e229 with wine-6.20 and WINEARCH=win32
Using native override for following DLLs: gdiplus
Executing wine regedit C:\windows\Temp\_native\override-dll.reg
002c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0034:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
003c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0048:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0060:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0078:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0084:err:seh:segv_handler Got unexpected trap -1
0084:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr 0x7f285300
003c:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
008c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0024:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
00ac:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
00b4:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
00bc:err:seh:segv_handler Got unexpected trap -1
00bc:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr 0x7f285300
00bc:err:seh:segv_handler Got unexpected trap -1
00bc:err:seh:segv_handler Got unexpected trap -1
00bc:err:seh:segv_handler Got unexpected trap -1
00bc:err:seh:segv_handler Got unexpected trap -1
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Executing w_do_call sound=alsa
Executing mkdir -p /home/wine
Executing load_sound alsa
Setting sound driver to alsa
Executing wine regedit C:\windows\Temp\set-sound.reg
0114:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
011c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0124:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
012c:err:seh:segv_handler Got unexpected trap -1
012c:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr 0x7f285300
012c:err:seh:segv_handler Got unexpected trap -1
012c:err:seh:segv_handler Got unexpected trap -1
012c:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr (nil)
012c:err:seh:segv_handler Got unexpected trap -1
012c:err:seh:segv_handler Got unexpected trap -1
Got unexpected trap -1
012c:err:seh:NtRaiseException Unhandled exception code 80000003 flags 0 addr 0x7f280a7e
012c:err:seh:segv_handler Got unexpected trap -1
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Using  override for following DLLs: winegstreamer
Executing wine regedit C:\windows\Temp\_disabled\override-dll.reg
0134:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
013c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0144:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
014c:err:seh:segv_handler Got unexpected trap -1
014c:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr 0x7f285300
Using  override for following DLLs: wmp
Executing wine regedit C:\windows\Temp\_disabled\override-dll.reg
0154:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
015c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0164:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
016c:err:seh:segv_handler Got unexpected trap -1
016c:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr 0x7f285300
016c:err:seh:segv_handler Got unexpected trap -1
wineboot
0174:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
017c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
017c:err:wineboot:ProcessStartupItems Couldn't get desktop folder.
/bin/mkdir: created directory '/home/wine/.wine/host/wine/AppData/LocalLow'
THERE IS AN ISSUE WITH DOTNET!
Trying to fix it..., wait a moment
wineserver -k
00a0:err:seh:segv_handler Got unexpected trap -1
00a0:err:seh:segv_handler Got unexpected trap -1
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
curl -fOL https://github.com/pauleve/docker-mtgo/raw/master/extra/mscoreei.dll
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   145  100   145    0     0    283      0 --:--:-- --:--:-- --:--:--   287
100  484k  100  484k    0     0   474k      0  0:00:01  0:00:01 --:--:-- 1592k
wine /opt/mtgo/mtgo.exe
002c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0034:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
003c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0048:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0060:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0078:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0084:err:seh:segv_handler Got unexpected trap -1
0084:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr 0x7f285300
003c:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
008c:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
0024:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f130000), expect trouble
00ac:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f230000), expect trouble
00b8:err:seh:segv_handler Got unexpected trap -1
00b8:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr 0x7f285300
00b8:err:seh:segv_handler Got unexpected trap -1
00b8:err:seh:segv_handler Got unexpected trap -1
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
0024:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040154 for dll L"mscoree.dll"
0024:err:ole:com_get_class_object no class object {1e66f26b-79ee-11d2-8710-00c04f79ed0d} could be created for context 0x1
00c0:err:seh:segv_handler Got unexpected trap -1
00c0:err:seh:NtRaiseException Unhandled exception code c000001d flags 0 addr 0x7f185300
/usr/local/bin/mtgo: line 16:  2650 Killed                  "${@}"
00d4:err:seh:segv_handler Got unexpected trap -1
00d4:err:seh:segv_handler Got unexpected trap -1
qemu: uncaught target signal 11 (Segmentation fault) - core dumped`

**Comment by pauleve** [comment] 2021-11-22 14:04
Strange. Might be related to M1. You may try again (do Ctrl+C or run `docker kill mtgo_running` in another terminal to force termination of the current command); or try an older version:
```
PATH=/opt/homebrew/Cellar/gnu-getopt/2.37.2/bin/:$PATH ./run-mtgo panard/mtgo:2021-07-24
```
If it doesn't work, please open a separate issue with the output.
You can redirect the output to a file you can join directly to the issue by doing
```
PATH=/opt/homebrew/Cellar/gnu-getopt/2.37.2/bin/:$PATH ./run-mtgo &>output.log
```
(then drag&drop the file 'output.log')

**Comment by mbenzvi** [comment] 2021-11-22 15:08
Thank you for your help, sadly it did not work so I am opening a new issue. The original issue is resolved, thoug!
Thank you for showing me how to output to a log directly!

**Comment by pauleve** [comment] 2021-11-22 15:16
Thanks for the feedback. I'm closing this issue then.
@jlessard93 if the reset didn't help, please open a separate issue as well, so we can keep track of our progress :-)

**Closed by pauleve** 2021-11-22 15:16 UTC
Labels: macOS
