### ISSUE TITLE
Update to Wine 3.X

### ISSUE THREAD

**Issue by Goles** [pauleve/docker-mtgo#18] opened 2018-02-07 07:19 UTC
.

**Comment by pauleve** [comment] 2018-02-07 11:06
There is an experimental image using wine 3.0 you can use with
`./run-mtgo panard/mtgo:sound`
but as not all patches for MTGO are integrated yet, I prefer to wait a bit and not break a working setup (as far as I know, wine 3.0 does not bring any noticeable improvement for MTGO, so nothing urgent).

**Comment by theli-ua** [comment] 2018-02-09 23:42
FWIW there is also not a lot of point in sticking to staging either, it seems to be on hiatus these days. And at the same time after this patch is merged https://source.winehq.org/patches/data/141282  the only remaining required for MTGO patchest would be gdi32-MultiMonitor one that so far applies cleanly to wine's master.

All in all non-staging should be more stable as staging contains often incomplete and sometimes even wrong patches.

**Comment by pauleve** [comment] 2018-02-10 10:43
The image `panard/mtgo:wine3` is based on wine 3.1 with the missing patches on top of it (winecodecs and multimonitor). But I have very little time for testing/playing currently, so I'll wait a bit before making it the default one.

**Comment by pauleve** [comment] 2018-02-17 10:37
@theli-ua just experienced a crash at some point after browsing collection and going to another tab, apparently related to windowscodecs. I join the backtrace. It was on wine-3.2 + the 3 patches in https://github.com/pauleve/docker-mtgo/tree/wine3/docker-wine.
[backtrace.txt](https://github.com/pauleve/docker-mtgo/files/1733577/backtrace.txt)

**Comment by theli-ua** [comment] 2018-02-17 18:05
@pauleve would it be possible to include/not strip debugging information for wine you build for docker?
That would provide more meaningful backtraces and help debug the issue

**Comment by pauleve** [comment] 2018-02-17 18:44
I'll try to do that, indeed. I hope to be able to reproduce it easily. Also, I'll update the windowscodecs patch with your latest changes.

**Comment by theli-ua** [comment] 2018-02-18 07:58
@pauleve also, that version of a patch could go out of arrays' bounds. Please update it to this one:
https://source.winehq.org/patches/data/141888

**Comment by theli-ua** [comment] 2018-02-18 08:01
sorry, I just realised you already said you'll update it >_<

**Comment by pauleve** [comment] 2018-02-23 21:37
The updated patch seems to fix the crash issue. The default image is now based on Wine 3.2

**Closed by pauleve** 2018-02-23 21:37 UTC
Labels: enhancement

**Comment by theli-ua** [comment] 2018-03-03 00:56
just FYI  windowscodecs patch has been accepted and is included with Wine 3.3
