### ISSUE TITLE
Error `Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"`

### ISSUE THREAD

**Issue by Uzay-G** [pauleve/docker-mtgo#81] opened 2020-03-25 22:52 UTC
Hey! I had started using this image since yesterday and everything was working fine but since a few hours ago it stopped working. The new error I am getting is `Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"`. Does anyone know how I can fix this?

I am using Ubuntu by the way.

Thanks!

**Comment by pauleve** [comment] 2020-03-26 09:05
Duplicate of #79

**Closed by pauleve** 2020-03-26 09:05 UTC
