### ISSUE TITLE
Docker container closes shortly after login

### ISSUE THREAD

**Issue by bigdiggysquiggle** [pauleve/docker-mtgo#66] opened 2019-08-24 23:29 UTC
I just updated to the most recent docker container and now shortly after login it disconnects. Issue appears to happen either within seconds of logging in or as soon as it attempts to communicate with the servers. I'm running this on Arch on all the latest packages with the latest version of docker and all that. Here's the error log:

005e:err:winediag:wined3d_dll_init Disabling 3D support.
0053:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0053:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0053:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"
005b:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
005b:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0068:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0068:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
006f:err:mmdevapi:DllGetClassObject Driver initialization failed
006f:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\windows\system32\mmdevapi.dll"
006f:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006f:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006f:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\windows\system32\winegstreamer.dll"
006f:err:ole:create_server class {f9d8d64e-a144-47dc-8ee0-f53498372c29} not registered
006f:err:ole:CoGetClassObject no class object {f9d8d64e-a144-47dc-8ee0-f53498372c29} could be created for context 0x17
006f:err:mmdevapi:DllGetClassObject Driver initialization failed
006f:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\windows\system32\mmdevapi.dll"
006f:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006f:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006f:err:mmdevapi:DllGetClassObject Driver initialization failed
006f:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\windows\system32\mmdevapi.dll"
006f:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006f:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006f:err:quartz:DSoundRender_create Cannot create Direct Sound object (80070057)
006f:err:mmdevapi:DllGetClassObject Driver initialization failed
006f:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\windows\system32\mmdevapi.dll"
006f:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006f:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006f:err:quartz:DSoundRender_create Cannot create Direct Sound object (80070057)
006f:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\windows\system32\winegstreamer.dll"
006f:err:ole:create_server class {728dcf55-128f-4dd1-ad22-becfa66ce7aa} not registered
006f:err:ole:CoGetClassObject no class object {728dcf55-128f-4dd1-ad22-becfa66ce7aa} could be created for context 0x17
006f:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\windows\system32\winegstreamer.dll"
006f:err:ole:create_server class {334b2ec9-f2b5-40b9-8432-4a00e00386a8} not registered
006f:err:ole:CoGetClassObject no class object {334b2ec9-f2b5-40b9-8432-4a00e00386a8} could be created for context 0x17
006f:err:mmdevapi:DllGetClassObject Driver initialization failed
006f:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\windows\system32\mmdevapi.dll"
006f:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006f:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006f:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\windows\system32\winegstreamer.dll"
006f:err:ole:create_server class {f9d8d64e-a144-47dc-8ee0-f53498372c29} not registered
006f:err:ole:CoGetClassObject no class object {f9d8d64e-a144-47dc-8ee0-f53498372c29} could be created for context 0x17
006f:err:mmdevapi:DllGetClassObject Driver initialization failed
006f:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\windows\system32\mmdevapi.dll"
006f:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006f:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006f:err:mmdevapi:DllGetClassObject Driver initialization failed
006f:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\windows\system32\mmdevapi.dll"
006f:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006f:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006f:err:quartz:DSoundRender_create Cannot create Direct Sound object (80070057)
006f:err:mmdevapi:DllGetClassObject Driver initialization failed
006f:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\windows\system32\mmdevapi.dll"
006f:err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
006f:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
006f:err:quartz:DSoundRender_create Cannot create Direct Sound object (80070057)
006f:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\windows\system32\winegstreamer.dll"
006f:err:ole:create_server class {728dcf55-128f-4dd1-ad22-becfa66ce7aa} not registered
006f:err:ole:CoGetClassObject no class object {728dcf55-128f-4dd1-ad22-becfa66ce7aa} could be created for context 0x17
006f:err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\windows\system32\winegstreamer.dll"
006f:err:ole:create_server class {334b2ec9-f2b5-40b9-8432-4a00e00386a8} not registered
006f:err:ole:CoGetClassObject no class object {334b2ec9-f2b5-40b9-8432-4a00e00386a8} could be created for context 0x17
006b:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0089:err:ole:CoGetContextToken apartment not initialised
0085:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
008d:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
008d:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0091:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0091:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0091:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
0091:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733

**Comment by pauleve** [comment] 2019-08-26 08:39
I cannot reproduce it... It looks like a network connectivity issue..
You may try the following:
```
./run-mtgo --shell
mtgo
```
to disable the auto-closing of container, let me know if that helps..

**Comment by bigdiggysquiggle** [comment] 2019-08-26 08:59
One of the times I tried running mtgo that way I had an error message pop up explaining that it thinks it doesn't have enough memory to run mtgo. It doesn't do that consistently though. In any case if you aren't able to replicate it then it's likely an issue with either my clone of the repo or my docker install itself. I'll check back if it continues to be a problem after going through a bunch of troubleshooting.

**Comment by pauleve** [comment] 2020-03-31 21:03
Closing old and probably outdated bugs. Please reopen if it is happening again.

**Closed by pauleve** 2020-03-31 21:03 UTC

**Comment by maurerf** [comment] 2020-09-23 14:42
Having what seems to be the exact same errors. Happened after updating to the latest MTGO version (might have missed a few versions in between, so that's not necessarily the cause). Tried reinstalling, updating wine and winetricks. One thing that's weird: even though winetricks --version gives me the most up-to-date version, the script seems to use winetricks-20191224.

Pastebin containing error code: https://pastebin.com/PRazVzee

**Comment by pauleve** [comment] 2020-09-23 19:15
make sure you are doing `./run-mtgo --update`. Then please open a new issue with the full output, as you did here (but the image you are using is outdated).
