### ISSUE TITLE
Crash right after launch, EULA related

### ISSUE THREAD

**Issue by kstefanini** [pauleve/docker-mtgo#85] opened 2020-03-29 14:06 UTC
Hi all, 
I've installed a fresh docker image, reboot computer, and then I get a crash after lauch, when EULA window showing.

`./run-mtgo > log2.txt`
Log is attached :
[log2.txt](https://github.com/pauleve/docker-mtgo/files/4399028/log2.txt)

Error seems to be here :
```
008a:err:quartz:BaseMemAllocator_Commit fnAlloc failed with error 0x8004020e
008a:err:eventlog:ReportEventW L"Application: MTGO.exenFramework Version: v4.0.30319nDescription: The process was terminated due to an unhandled exception.nException Info: exception code c0000005, exception address F441CB14n"
wine: Unhandled page fault on read access to 0x00000000 at address 0xf441cb14 (thread 008a), starting debugger...
```

Do you have an idea how to fix this ?

Thanks !

**Comment by pauleve** [comment] 2020-03-29 14:19
On a fresh install you need to run the docker twice to get the fix. Does it still occurs if you try again (without any reset)?

**Comment by kstefanini** [comment] 2020-03-29 14:23
Already ran it 3 times before log. Tried one more time, but still crashing after EULA window showing

**Comment by pauleve** [comment] 2020-03-29 14:25
And if you add `panard/mtgo:pr73`?

**Comment by pauleve** [comment] 2020-03-29 14:28
This is a duplicate of #83, let's continue the discussion there. I'll add the workaround to bypass EULA later today, might actually help..

**Closed by pauleve** 2020-03-29 14:28 UTC
Labels: duplicate

**Comment by kstefanini** [comment] 2020-03-29 15:43
Thanks, it works with `./run-mtgo --update panard/mtgo:pr73`
 Sorry for the duplicate

**Comment by pauleve** [comment] 2020-03-29 15:46
Thanks for the feedback!
