### ISSUE TITLE
latest is failing for me but issue102 works fine

### ISSUE THREAD

**Issue by fugit** [pauleve/docker-mtgo#104] opened 2020-09-20 18:20 UTC
I am having the same problem that 'Greginator' reported with the panard/mtgo:latest(=panard/mtgo:2020-09-18) release running wine-5.17. I am able to play using issue102 with wine-5.12. Please find my log attached. The launch just hangs when it reaches the below error. I let it run for about 15m and it was still hanging at that message when I came back. Previous issues(#79) mentions this can normally be ignored.
```
012c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
```

[output.log](https://github.com/pauleve/docker-mtgo/files/5251090/output.log)

I also tried pr95, and pr99, neither of those worked.

Extra info:
```
dpkg --list | grep docker
ii  docker-ce                                                   5:19.03.12~3-0~debian-buster                 amd64        Docker: the open-source application container engine
ii  docker-ce-cli                                               5:19.03.12~3-0~debian-buster                 amd64        Docker CLI: the open-source application container engine
```
```
uname -a
Linux hostname 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```

Thanks for all your time and effort in maintaining.

**Comment by pauleve** [comment] 2020-09-20 20:05
Thanks for the report. I've put the `issue102` image as the default one the time to solve this issue..
Could you try with the following command:
```
./run-mtgo --reset --test panard/mtgo:2020-09-18
```

**Comment by fugit** [comment] 2020-09-20 21:57
> Thanks for the report. I've put the `issue102` image as the default one the time to solve this issue..

Great thanks.

> Could you try with the following command:

Sure:
```
/home/keith/repos/github.com/pauleve/docker-mtgo/run-mtgo --reset --test panard/mtgo:2020-09-18
WARNING: You are about to delete /home/keith/.local/share/mtgo-test and wipe docker volume mtgo-data-keith-test
Press Enter to continue, CTRL+C to abort

docker volume rm mtgo-data-keith-test
Error: No such volume: mtgo-data-keith-test
docker volume create mtgo-data-keith-test
mtgo-data-keith-test
docker run --rm -v mtgo-data-keith-test:/home/wine/.wine/host panard/mtgo:2020-09-18 true
Unable to find image 'panard/mtgo:2020-09-18' locally
2020-09-18: Pulling from panard/mtgo
Digest: sha256:4d5e29c26ae6b5fbd2f5a2c64a0e775a77c5d5c387403af4c71d56521ae1aa1d
Status: Downloaded newer image for panard/mtgo:2020-09-18
docker run --privileged --rm -e DISPLAY -v mtgo-data-keith-test:/home/wine/.wine/host/ -v mtgo-data-keith-test:/home/wine/.wine/drive_c/users/ -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /home/keith/.local/share/mtgo-test/Xauthority:/home/wine/.Xauthority:ro --net=host --ipc=host -e TZ=/usr/share/zoneinfo/America/New_York --name mtgo_running panard/mtgo:2020-09-18 mtgo
winetricks gdiplus=native sound=alsa winegstreamer=disabled wmp=disabled
Executing mkdir -p /home/wine
Using winetricks 20200412-next - sha256sum: fad7d983b413389590c39d8de38040c2d36a3e374a7c842c4051e11afc8fe44b with wine-5.17 and WINEARCH=win32
Using native override for following DLLs: gdiplus
Executing wine regedit C:windowsTemp_nativeoverride-dll.reg
Executing w_do_call sound=alsa
Executing mkdir -p /home/wine
Executing load_sound alsa
Setting sound driver to alsa
Executing wine regedit C:windowsTempset-sound.reg
Using override for following DLLs: winegstreamer
Executing wine regedit C:windowsTemp_disabledoverride-dll.reg
Using override for following DLLs: wmp
Executing wine regedit C:windowsTemp_disabledoverride-dll.reg
wineboot
wine /opt/mtgo/mtgo.exe
0114:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 011c), starting debugger...
```
It just hangs there.

Procs running in the container:
```
    1 wine      20   0    3960   2888   2712 S   0.0   0.0   0:00.00 mtgo                                                                                                                                                                                               
   67 wine      20   0   11536  10668   1916 S   0.0   0.1   0:00.45 wineserver                                                                                                                                                                                         
   73 wine      20   0 2654076  17912   5368 S   0.0   0.1   0:00.02 services.exe                                                                                                                                                                                       
   76 wine      20   0 2655208  18012   6496 S   0.0   0.1   0:00.01 winedevice.exe                                                                                                                                                                                     
   83 wine      20   0 2657488  21060   6696 S   0.0   0.1   0:00.02 plugplay.exe                                                                                                                                                                                       
   89 wine      20   0 2652824  19416   5724 S   0.0   0.1   0:00.02 winedevice.exe                                                                                                                                                                                     
  863 wine      20   0 3860900  28696  11644 S   0.0   0.2   0:00.03 mtgo.exe                                                                                                                                                                                           
  866 wine      20   0 2657284  21244   8828 S   0.0   0.1   0:00.02 explorer.exe                                                                                                                                                                                       
  869 wine      20   0 2654544  18832   6984 S   0.0   0.1   0:00.02 winedbg                                                                                                                                                                                            
  879 root      20   0    4092   3068   2768 S   0.0   0.0   0:00.01 bash  
```

Let me know if any other info would be helpful.

**Comment by pauleve** [comment] 2020-09-21 08:23
I can reproduce the bug on another computer. This might be related to display driver/screen detection..

**Comment by fugit** [comment] 2020-09-21 11:57
> I can reproduce the bug on another computer. This might be related to display driver/screen detection..

Here is my current info, happy to try with different drivers/resolution or new image.

```
xrandr | grep -A1 ' connected'
DP-4 connected 3440x1440+0+0 (normal left inverted right x axis y axis) 798mm x 335mm
   3440x1440     59.97 + 100.00*   94.99    89.96    84.96    79.98    49.99

dpkg --list | grep -i '^ii  nvidia-driver '
ii  nvidia-driver                                               418.152.00-1                                 amd64        NVIDIA metapackage 
```

**Comment by pauleve** [comment] 2020-09-21 12:43
Should be fixed by `panard/mtgo:pr105` image (#105)

**Comment by Greginator** [comment] 2020-09-21 13:13
Confirming `./run-mtgo panard/mtgo:pr105` works for me

**Comment by fugit** [comment] 2020-09-21 13:20
Confirming `./run-mtgo panard/mtgo:pr105` works for me as well. I'll be able to test more later today.

**Comment by pauleve** [comment] 2020-09-21 13:36
@Greginator regarding the flickering and focus, can you try adding `--winecfg` option to `./run-mtgo` and then in Graphics select "Emulate a virtual desktop" with the appropriate resolution? Anyway, this looks like a regression introduced by the newly installed libx libraries..

**Comment by Greginator** [comment] 2020-09-21 14:01
Doing that works and solves the flickering however it now is locked into that aspect ratio whenever the program is open. With the old wine version it could simply be dragged around like a normal window.

Here is an example of what I am seeing without emulate virtual desktop turned on. I wondered if this is something to do with being on a dual monitor setup however that doesn't seem to be the case. When I turn off the second monitor the window still flickers in this manner. I have taken a video to show you what I am seeing: https://a.uguu.se/muephc.webm

**Comment by pauleve** [comment] 2020-09-21 14:44
Thanks for the video, very interesting :-)
Can you do
```
./run-mtgo -e WINEDEBUG=+x11drv,+winex11 panard/mtgo:pr105 &>output-pr105.log
./run-mtgo -e WINEDEBUG=+x11drv,+winex11 panard/mtgo:issue102 &>output-issue102.log
```
and post the log files?

**Comment by Greginator** [comment] 2020-09-21 14:54
here you go
[output-issue102.log](https://github.com/pauleve/docker-mtgo/files/5256174/output-issue102.log)
[output-pr105.log](https://github.com/pauleve/docker-mtgo/files/5256175/output-pr105.log)

**Comment by pauleve** [comment] 2020-09-21 20:24
I tried on a fresh Ubuntu and had no issue.. (single monitor though). What is your distribution and desktop environment?

**Comment by Greginator** [comment] 2020-09-21 20:30
Cinnamon on Ubuntu 20.04 (not mint)

**Comment by pauleve** [comment] 2020-09-21 20:32
I just noticed that one of important differences between your two log files is that in issue102 only one monitor is detected, but two with pr105. Could be a bug in wine actually...

**Comment by pauleve** [comment] 2020-09-21 20:45
(sorry for the split comments)
I'll debug with a second monitor later, but in the meantime, I'm interested in the following experiment:
In one term, `./run-mtgo --shell panard/mtgo:pr105`
In another term, `docker exec -it -u root mtgo_running apt remove libxinerama1`
Then, in the first term, `/usr/local/bin/mtgo`
Is the window (re)positioning bug still occuring?

**Comment by fugit** [comment] 2020-09-21 21:34
@pauleve Everything looks good for me using `./run-mtgo panard/mtgo:pr105`.

Thanks.

**Comment by Greginator** [comment] 2020-09-22 11:08
> (sorry for the split comments)
> I'll debug with a second monitor later, but in the meantime, I'm interested in the following experiment:
> In one term, `./run-mtgo --shell panard/mtgo:pr105`
> In another term, `docker exec -it -u root mtgo_running apt remove libxinerama1`
> Then, in the first term, `/usr/local/bin/mtgo`
> Is the window (re)positioning bug still occuring?
Just got around to testing this out. Yes I am still getting the same positioning bug I showed sadly.

**Comment by pauleve** [comment] 2020-09-26 13:03
@Greginator I just tried with a multi-monitor setup, and got no positioning issue.. 
Can you try if it happens with winecfg window as well? (`./run-mtgo panard/mtgo:pr105 --winecfg`)
If it does, it may be worth trying with the wine-devel package from ubuntu, outside docker.. (just install winehq-devel and run winecfg).

**Comment by Greginator** [comment] 2020-09-27 11:51
The winecfg window does not have this issue. The issue is quite weird, it might be a WM specific issue with mtgo.

**Comment by pauleve** [comment] 2020-09-28 19:53
Indeed, using Cinnamon I'm able to reproduce your bugs, even with vanilla wine outside Docker. I'll make more debug later and open an issue upstream.

**Comment by pauleve** [comment] 2020-09-30 11:40
So the issue looks already reported upstream, on a different program: https://bugs.winehq.org/show_bug.cgi?id=49779 again occurring with Cinnamon.
I posted some debug info there, let's see what happens :smile:

**Comment by pauleve** [comment] 2020-09-30 11:43
Let's move this issue to #108

**Closed by pauleve** 2020-09-30 11:43 UTC
Labels: bug
