### ISSUE TITLE
MTGO slow and freezes after every action

### ISSUE THREAD

**Issue by ralacerda** [pauleve/docker-mtgo#121] opened 2021-05-18 20:17 UTC
Hi Guys,
I tried to play with this version of MTGO, I'm currently on Linux. I get a good performance out of Magic Arena, so I don't think MTGO being slow is due to my hardware.       

So the game is slow to open tabs, but that is okay, the real problem is that in game, everything freezes for 10-20 seconds after every action. If my opponents plays a card, I see the card in chat, but it takes 10-20 seconds to show up, while everything is freezed. I played a best of three, and I noticed it gets better during game 2, but it will still randomly freeze for the 10-20 seconds. 

Kind of a pain to play like this (specially for my opponent), when the game starts, it takes 30 seconds before I can pick if I want to play first or not.

Here is the logs of running
```./run-mtgo --debug &>output.log```

https://gist.github.com/ralacerda/8b97718b840df5705064d767df9a4b08

Thanks everyone

**Comment by pauleve** [comment] 2021-05-18 21:58
Probably duplicate of #107. You can try a few things from the comments there, but this is indeed a known issue on some systems.  The first thing to try is using an older image:
`./run-mtgo panard/mtgo:wine-4.9`

It seems unrelated to the performance of the system, and it is difficult to reproduce on different machines (in my case I cannot reproduce it although I tried on 3 different machines..).
If you post your `docker info` and details on your setup (linux distribution, window manager), it may help finding a rational.

**Comment by pauleve** [comment] 2022-10-19 07:43
Closing old inactive bugs. Feel free to open a new issue if still occurring, with info on Linux distribution, window manager, graphics card, and docker info

**Closed by pauleve** 2022-10-19 07:43 UTC
